# Generated by Django 2.0.7 on 2018-08-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='song',
            field=models.ManyToManyField(through='history.Album_Song', to='history.Song'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='year_started',
            field=models.CharField(default=' ', max_length=4),
        ),
    ]
